---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: power-tools
  title: PowerTools
  description: PowerTools packages for applications.
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: library
  owner: heroes-for-hire
  lifecycle: production
  system: power-application-framework
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nitro_config
  title: Nitro Config
  description: >-
    When included in a Rails application, NitroConfig loads the configuration
    file at `config/config.yml` within the application directory and makes
    its values available at `NitroConfig.config`. Config values are loaded
    based on the Rails environment, permitting the specification of
    multiple environments' configurations in a single file.
  annotations:
    backstage.io/techdocs-ref: dir:packages/nitro_config
spec:
  type: library
  owner: heroes-for-hire
  lifecycle: production
  subcomponentOf: power-tools
  system: power-application-framework
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: audit_tracker
  title: Audit Tracker
  description: >-
    AuditTracker helps you centralize data tracking configuration to be used
    across different models
  annotations:
    backstage.io/techdocs-ref: dir:packages/audit_tracker
spec:
  type: library
  owner: heroes-for-hire
  lifecycle: production
  subcomponentOf: power-tools
  system: power-application-framework
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lumberaxe
  title: Lumberaxe
  description: Handles logging output formatting
  annotations:
    backstage.io/techdocs-ref: dir:packages/lumberaxe
spec:
  type: library
  owner: heroes-for-hire
  lifecycle: production
  subcomponentOf: power-tools
  system: power-application-framework
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: consent
  title: Consent
  description: Permission-based authorization
  annotations:
    backstage.io/techdocs-ref: dir:packages/consent
spec:
  type: library
  owner: heroes-for-hire
  lifecycle: production
  subcomponentOf: power-tools
  system: power-application-framework
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: eslint-config-powerhome
  title: ESLint Config Powerhome
  description: Provides eslint-config for Power Home Remodeling apps
  annotations:
    backstage.io/techdocs-ref: dir:packages/eslint-config
spec:
  type: library
  owner: heroes-for-hire
  lifecycle: production
  subcomponentOf: power-tools
  system: power-application-framework
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rubocop-cobra
  title: Rubocop Cobra
  description: Gem focused on providing Cops to support a healthy cobra app development
  annotations:
    backstage.io/techdocs-ref: dir:packages/rubocop-cobra
spec:
  type: library
  owner: heroes-for-hire
  lifecycle: production
  subcomponentOf: power-tools
  system: power-application-framework
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rubocop-powerhome
  title: Rubocop Powerhome
  description: Gem focused on providing standard Rubocop configuration for Power Home Remodeling ruby apps
  annotations:
    backstage.io/techdocs-ref: dir:packages/rubocop-powerhome
spec:
  type: library
  owner: heroes-for-hire
  lifecycle: production
  subcomponentOf: power-tools
  system: power-application-framework
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cygnet
  title: Something for Nothing
  description: >-
    Naughty is comprised of two parts.
    An implementation of the Null Object Pattern and
    an implementation of nested hashes using DeepStruct.
spec:
  type: library
  owner: heroes-for-hire
  system: power-application-framework
  lifecycle: production
  subcomponentOf: power-tools
