# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in rubocop-cobra.gemspec
gemspec

gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "rubocop", "~> 1.35.0"

gem "rubocop-powerhome", path: "../rubocop-powerhome"
