require:
  - rubocop-powerhome

AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false

Style/FrozenStringLiteralComment:
  Exclude:
    - "gemfiles/*"

Bundler/OrderedGems:
  Exclude:
    - "gemfiles/*"

Metrics/BlockLength:
  Exclude:
    - "spec/dummy/db/schema.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
    - "spec/dummy/db/migrate/*"

Rails:
  Enabled: false
