inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-powerhome

AllCops:
  TargetRubyVersion: 3.0

Rails/ActionFilter:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Rails/HelperInstanceVariable:
  Exclude:
    - 'lib/cygnet/collections.rb'

Rails/EnvironmentVariableAccess:
  Exclude:
    - 'spec/spec_helper.rb'
