---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nitro-naughty
  title: Nitro Naughty
  description: >-
    Naughty is comprised of two parts.
    An implementation of the Null Object Pattern and
    an implementation of nested hashes using DeepStruct.
spec:
  type: library
  owner: heroes-for-hire
  system: nitro
  lifecycle: production
  subcomponentOf: nitro-web
  dependsOn:
    - component:nitro-linting
