module.exports = {
  root: true,
  plugins: ["jsx-control-statements", "react", "react-hooks"],
  extends: [
    "eslint:recommended",
    "plugin:jsx-control-statements/recommended",
    "plugin:react/recommended",
    "plugin:react-hooks/recommended",
  ],
  parser: "babel-eslint",
  parserOptions: {
    ecmaVersion: 6,
    sourceType: "module",
    ecmaFeatures: {
      jsx: true,
    },
  },
  env: {
    browser: true,
    es6: true,
    "jsx-control-statements/jsx-control-statements": true,
    node: true,
    mocha: true,
  },
  rules: {
    "jsx-control-statements/jsx-jcs-no-undef": 1,
    "no-console": 1,
    "no-restricted-globals": [1, { name: "moment" }],
    "no-use-before-define": [2, { functions: true, classes: true }],
    "react/forbid-prop-types": 2,
    "react/jsx-boolean-value": 2,
    "react/jsx-closing-bracket-location": 1,
    "react/jsx-curly-spacing": 2,
    "react/jsx-handler-names": 2,
    "react/jsx-indent-props": 2,
    "react/jsx-key": 2,
    "react/jsx-max-props-per-line": 2,
    "react/jsx-no-bind": 0,
    "react/jsx-no-literals": 1,
    "react/jsx-no-undef": [2, { allowGlobals: true }],
    "react/jsx-pascal-case": 2,
    "react/jsx-sort-props": 2,
    "react/jsx-wrap-multilines": 2,
    "react/no-danger": 1,
    "react/no-did-mount-set-state": 2,
    "react/no-did-update-set-state": 2,
    "react/no-multi-comp": 1,
    "react/no-set-state": 1,
    "react/prefer-es6-class": 2,
    "react/prop-types": 1,
    "react/self-closing-comp": 2,
    "react/sort-comp": 1,
  },
  settings: {
    react: {
      version: "detect",
    },
  },
  ignorePatterns: [
    "**/*.d.ts",
    "coverage/**/*",
    "doc/**/*",
    "node_modules/**/*",
    "spec/dummy/**/*",
    "vendor/**/*",
  ],
}
