require:
  - rubocop-powerhome

AllCops:
  TargetRubyVersion: 3.0

Metrics/MethodLength:
  Exclude:
    - spec/**/*_spec.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - 'gemfiles/*'

Bundler/OrderedGems:
  Exclude:
    - 'gemfiles/*'
