inherit_from: .rubocop_todo.yml

require:
  - rubocop-powerhome

AllCops:
  TargetRubyVersion: 3.0

Metrics/MethodLength:
  Exclude:
    - spec/**/*_spec.rb

Rails/ActionFilter:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/SaveBang:
  Enabled: false