require:
  - rubocop-powerhome

Naming/FileName:
  Exclude:
    - lib/rubocop-powerhome.rb

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'rubocop-powerhome.gemspec'

Rails:
  Enabled: false
