# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in rubocop-powerhome.gemspec
gemspec

gem "rake", "~> 13.0"
gem "rspec", "~> 3.0"
gem "rubocop", "~> 1.29.1"
gem "rubocop-performance"
gem "rubocop-rails"
gem "rubocop-rake"
gem "rubocop-rspec"
