---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: lumberaxe
  title: Lumberaxe
  description: Handles logging output formatting
spec:
  type: library
  owner: heroes-for-hire
  system: nitro
  lifecycle: production
  subcomponentOf: nitro-web
  dependsOn:
    - component:nitro-linting
