require:
  - rubocop-powerhome

AllCops:
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Exclude:
    - 'gemfiles/*'

Bundler/OrderedGems:
  Exclude:
    - 'gemfiles/*'

Rails:
  Enabled: false
