---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nitro-config
  title: Nitro Config
  description: >-
    When included in a Rails application, NitroConfig loads the configuration
    file at `config/config.yml` within the application directory and makes
    its values available at `NitroConfig.config`. Config values are loaded
    based on the Rails environment, permitting the specification of
    multiple environments' configurations in a single file.
spec:
  type: library
  owner: heroes-for-hire
  system: nitro
  lifecycle: production
  subcomponentOf: nitro-web
  dependsOn:
    - component:nitro-linting
