inherit_from:
  - .rubocop_todo.yml

require:
  - rubocop-powerhome

Rails/ActionFilter:
  Enabled: false

Rails/ActionOrder:
  Enabled: false

Rails/EnvironmentVariableAccess:
  Exclude:
    - 'spec/**/*'

AllCops:
  TargetRubyVersion: 3.0
