site_name: Rubocop Powerhome
site_description: Gem focused on providing standard Rubocop configuration for Power Home Remodeling ruby apps
repo_url: https://github.com/powerhome/power_linting
edit_uri: edit/main/rubocop_powerhome/docs/
nav:
  - 'Home': 'README.md'

plugins:
  - techdocs-core
