require:
  - rubocop-powerhome

AllCops:
  TargetRubyVersion: 3.0

Style/FrozenStringLiteralComment:
  Exclude:
    - 'gemfiles/*'

Bundler/OrderedGems:
  Exclude:
    - 'gemfiles/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/internal/db/schema.rb'
    - 'spec/internal/db/test_dump_schema.rb'
    - 'data_taster.gemspec'

Rails:
  Enabled: false
