on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string
      ruby:
        required: true
        type: string
      rails:
        required: true
        type: string

env:
  PROJECT_DIR: ${{ format("packages/{0}", inputs.package) }}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ inputs.ruby }} / Rails ${{ inputs.rails }}
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby }}
          bundler-cache: true
          working-directory: ${{ env.PROJECT_DIR }}
        env:
          RAILS_VERSION: ${{ inputs.rails }}
      - name: Run the build script
        working-directory: ${{ env.PROJECT_DIR }}
        run: bundle exec rake
        env:
          RAILS_VERSION: ${{ inputs.rails }}
      - name: Ensure license compliance
        working-directory: ${{ env.PROJECT_DIR }}
        run: bundle exec license_finder

  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/tags/v') && contains(github.ref, inputs.package) }}
    steps:
      - uses: actions/checkout@v3
      - uses: xjunior/publish-rubygems-action@master
        env:
          RELEASE_COMMAND: rake build release:guard_clean release:rubygem_push
          GITHUB_TOKEN: ${{ secrets.github_token }}
          RUBYGEMS_API_KEY: ${{ secrets.rubygems_api_key }}
          WORKDIR: ${{ env.PROJECT_DIR }}
