on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

env:
  PROJECT_DIR: ${{ format("packages/{0}", inputs.package) }}

jobs:
  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/tags/v') && contains(github.ref, inputs.package) }}
    steps:
      - uses: actions/checkout@v3
      - uses: xjunior/publish-rubygems-action@master
        env:
          RELEASE_COMMAND: rake build release:guard_clean release:rubygem_push
          GITHUB_TOKEN: ${{ secrets.github_token }}
          RUBYGEMS_API_KEY: ${{ secrets.rubygems_api_key }}
          WORKDIR: ${{ env.PROJECT_DIR }}
