name: audit_tracker

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@main
    with:
      package: ${{ github.workflow }}
      workdir: "packages/${{ github.workflow }}"
      gemfiles: "['gemfiles/rails_6_1.gemfile','gemfiles/rails_7_0.gemfile','gemfiles/rails_7_1.gemfile','gemfiles/rails_7_2.gemfile']"
      ruby: '["3.0","3.3"]'
    secrets: inherit
