name: audit_tracker

on:
  push:

jobs:
  ruby:
    uses: ./.github/workflows/_ruby-package.yml
    with:
      package: ${{ github.workflow }}
      workdir: 'packages/${{ github.workflow }}'
      ruby: '["2.7", "3.1"]'
      rails: '["7.0","6.1","6.0","5.2"]'
    secrets: inherit
