name: audit_tracker

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.7.4'
          - '3.1.2'
        rails:
          - '7.0.3.1'
          - '6.1.6.1'
          - '6.0.5.1'
          - '5.2.8.1'
        exclude:
          - rails: '5.2.8.1'
            ruby: '3.1.2'
          - rails: '7.0.3.1'
            ruby: '2.7.4'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/_build-ruby
        with:
          package: ${{ github.workflow }}
          ruby: ${{ matrix.ruby }}
          rails: ${{ matrix.rails }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/_release-ruby
        with:
          package: ${{ github.workflow }}
