name: cygnet

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@main
    with:
      package: ${{ github.workflow }}
      workdir: "packages/${{ github.workflow }}"
      ruby: '["3.0","3.1","3.2","3.3"]'
      exclude: |-
        [
          { 'ruby': '3.0', 'gemfile': 'gemfiles/rails_7_2.gemfile'},
        ]
    secrets: inherit
