name: cygnet

on:
  push:

jobs:
  ruby:
    uses: ./.github/workflows/_ruby-workflow.yml
    with:
      package: ${{ github.workflow }}
      workdir: 'packages/${{ github.workflow }}'
    secrets: inherit
