name: data_taster

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@main
    with:
      package: ${{ github.workflow }}
      workdir: "packages/${{ github.workflow }}"
    secrets: inherit
