name: dep_shield

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@main
    with:
      package: ${{ github.workflow }}
      workdir: "packages/${{ github.workflow }}"
      gemfiles: "['gemfiles/rails_6_0.gemfile','gemfiles/rails_6_1.gemfile','gemfiles/rails_7_0.gemfile']"
      ruby: '["3.0","3.1","3.2","3.3"]'
      exclude: |-
        [
          { 'ruby': '3.2', 'gemfile': 'gemfiles/rails_6_0.gemfile'},
          { 'ruby': '3.3', 'gemfile': 'gemfiles/rails_6_0.gemfile'},
          { 'ruby': '3.2', 'gemfile': 'gemfiles/rails_6_1.gemfile'},
          { 'ruby': '3.3', 'gemfile': 'gemfiles/rails_6_1.gemfile'},
        ]
    secrets: inherit
