name: edgestitch

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@main
    with:
      package: ${{ github.workflow }}
      workdir: "packages/${{ github.workflow }}"
      before_build: sudo /etc/init.d/mysql start
      gemfiles: "['gemfiles/rails_6_0.gemfile','gemfiles/rails_6_1.gemfile','gemfiles/rails_7_0.gemfile']"
      ruby: '["3.0","3.1","3.2","3.3"]'
    secrets: inherit
