name: eslint-config

on:
  push:

jobs:
  node:
    uses: powerhome/github-actions-workflows/.github/workflows/yarn-package.yml@npm-license-compliance
    with:
      workdir: "packages/${{ github.workflow }}"
    secrets: inherit
