name: eslint-config

on:
  push:

jobs:
  node:
    uses: powerhome/github-actions-workflows/.github/workflows/yarn-package.yml@main
    with:
      package: ${{ github.workflow }}
      node: '["20", "22"]'
      workdir: "packages/${{ github.workflow }}"
    secrets: inherit
