name: eslint-config

on:
  push:

jobs:
  node:
    uses: powerhome/github-actions-workflows/.github/workflows/yarn-package.yml@main
    with:
      package: ${{ github.workflow }}
      workdir: "packages/${{ github.workflow }}"
      ruby: '["3.0","3.1","3.2","3.3"]'
    secrets: inherit
