name: nitro_config

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/ruby-gem.yml@main
    with:
      package: ${{ github.workflow }}
      workdir: "packages/${{ github.workflow }}"
      gemfiles: "['gemfiles/rails_6_0.gemfile','gemfiles/rails_6_1.gemfile','gemfiles/rails_7_0.gemfile']"
    secrets: inherit
