name: rubocop-cobra

on:
  push:

jobs:
  ruby:
    uses: ./.github/workflows/_ruby-package.yml
    with:
      package: ${{ github.workflow }}
      workdir: 'packages/${{ github.workflow }}'
      rails: '["any"]'
    secrets: inherit
