name: rubocop-powerhome

on:
  push:

jobs:
  ruby:
    uses: ./.github/workflows/_ruby-package.yml
    with:
      package: ${{ github.workflow }}
      workdir: 'packages/${{ github.workflow }}'
    secrets: inherit
