name: simple_trail

on:
  push:

jobs:
  ruby:
    uses: ./.github/workflows/_ruby-package.yml
    with:
      package: ${{ github.workflow }}
      workdir: 'packages/${{ github.workflow }}'
    secrets: inherit
    rails:
      default: '["6.1","6.0"]'
      required: false
      type: string

